---
- name: checkout grafana from git
  git: repo={{ grafana_git_url }}
       dest={{ grafana_root_path }}
       version={{ grafana_git_branch }}
       force=yes
       update=yes
  notify:
    - rebuild grafana {{ grafana_root_path }}
- name: make dist dir
  file: path={{ grafana_root_path }}/dist state=directory owner={{ grafana_owner }}
- name: make config for grafana
  template: src=grafana.js.j2 dest={{ grafana_root_path }}/dist/config.js owner={{ grafana_owner }}
