---
- name: make dist dir
  file: path={{ grafana_root_path }}/dist state=directory owner={{ grafana_owner }} recurse=yes
- name: download grafana
  get_url: dest={{ grafana_root_path}}/grafana-{{ grafana_version }}.tar.gz url=http://grafanarel.s3.amazonaws.com/grafana-{{ grafana_version }}.tar.gz
- name: extract grafana tarball
  command: tar zxf grafana-{{ grafana_version }}.tar.gz -C dist --strip-components=1 chdir={{ grafana_root_path }} creates={{ grafana_root_path }}/dist/README.md
  sudo_user: "{{ grafana_owner }}"
  sudo: true
- name: make config for grafana
  template: src=grafana.js.j2 dest={{ grafana_root_path }}/dist/config.js owner={{ grafana_owner }}